/**
 * Error codes describing various issues related to Dreamstate usage.
 * These error codes are used to categorize different types of errors.
 *
 * @enum {string}
 */
export enum EDreamstateErrorCode {
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  RESTRICTED_OPERATION = "RESTRICTED_OPERATION",
  INSTANCE_DISPOSED_LIFECYCLE = "INSTANCE_DISPOSED_LIFECYCLE",
  INSTANCE_DISPOSED_SCOPE = "INSTANCE_DISPOSED_SCOPE",
  OUT_OF_SCOPE = "OUT_OF_SCOPE",
  INCORRECT_PARAMETER = "INCORRECT_PARAMETER",
  INCORRECT_SIGNAL_LISTENER = "INCORRECT_SIGNAL_LISTENER",
  INCORRECT_SIGNAL_TYPE = "INCORRECT_SIGNAL_TYPE",
  INCORRECT_QUERY_PROVIDER = "INCORRECT_QUERY_PROVIDER",
  INCORRECT_QUERY_TYPE = "INCORRECT_QUERY_TYPE",
  TARGET_CONTEXT_MANAGER_EXPECTED = "TARGET_CONTEXT_MANAGER_EXPECTED",
}
