version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    working_directory: ~/dreamstate
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          name: Restoring node_modules cache
          key: 'v1-deps-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}'
      - run:
          name: 'Set user permissions'
          command: >-
            sudo chown -R $(whoami) $(npm config get
            prefix)/{lib/node_modules,bin,share}
      - run:
          name: 'Install pnpm'
          command: 'curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm'
      - run:
          name: Setup project dependencies
          command: 'pnpm install --frozen-lockfile'
      - save_cache:
          name: Saving node_modules cache
          key: 'v1-deps-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}'
          paths:
            - node_modules
            - cli/node_modules
            - src/dreamstate/node_modules
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build:dts
      - run: pnpm build:cjs
      - run: pnpm build:esm
      - run: pnpm build:ptb

workflows:
  build-and-test:
    jobs:
      - build-and-test
