version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    working_directory: ~/dreamstate
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}-v2
      - run:
          name: Install pnpm
          command: npm install pnpm
      - run:
          name: Setup project dependencies
          command: npx pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}-v2
          paths:
            - node_modules
            - cli/node_modules
            - src/dreamstate/node_modules
      - run:
          name: Lint
          command: pnpm lint
      - run:
          name: Typecheck
          command: pnpm typecheck
      - run:
          name: Test
          command: pnpm test
      - run:
          name: Build DTS
          command: pnpm build:dts
      - run:
          name: Build CJS
          command: pnpm build:cjs
      - run:
          name: Build ESM
          command: pnpm build:esm
      - run:
          name: Build PTB
          command: pnpm build:ptb

workflows:
  build-and-test:
    jobs:
      - build-and-test
